// packages/vue/src/Player.vue
<template>
  <div ref="container" />
</template>
<script lang="ts">
import {
  defineComponent,
  onMounted,
  ref,
  watch,
  PropType,
  onBeforeUnmount,
} from 'vue-demi'
import {
  VimeoPlayer,
  VimeoPlayerEvents,
  VimeoPlayerProperties,
  VIMEO_PLAYER_EVENTS,
} from '@vimeo-player/core'

export default defineComponent({
  name: 'VimeoPlayer',
  props: {
    video: {
      type: String as PropType<VimeoPlayerProperties['video']>,
      required: true,
    },
    paused: {
      type: Boolean as PropType<VimeoPlayerProperties['paused']>,
      default: true,
    },
    autopause: {
      type: Boolean as PropType<VimeoPlayerProperties['autopause']>,
      default: false,
    },
    autoplay: {
      type: Boolean as PropType<VimeoPlayerProperties['autoplay']>,
      default: false,
    },
    background: {
      type: Boolean as PropType<VimeoPlayerProperties['background']>,
      default: false,
    },
    controls: {
      type: Boolean as PropType<VimeoPlayerProperties['controls']>,
      default: false,
    },
    dnt: {
      type: Boolean as PropType<VimeoPlayerProperties['dnt']>,
      default: false,
    },
    loop: {
      type: Boolean as PropType<VimeoPlayerProperties['loop']>,
      default: false,
    },
    muted: {
      type: Boolean as PropType<VimeoPlayerProperties['muted']>,
      default: false,
    },
    responsive: {
      type: Boolean as PropType<VimeoPlayerProperties['responsive']>,
      default: true,
    },
    showByline: {
      type: Boolean as PropType<VimeoPlayerProperties['showByline']>,
      default: false,
    },
    showPortrait: {
      type: Boolean as PropType<VimeoPlayerProperties['showPortrait']>,
      default: false,
    },
    showTitle: {
      type: Boolean as PropType<VimeoPlayerProperties['showTitle']>,
      default: false,
    },
    speed: {
      type: Boolean as PropType<VimeoPlayerProperties['speed']>,
      default: false,
    },
    texttrack: {
      type: String as PropType<VimeoPlayerProperties['texttrack']>,
      default: 'en',
    },
    start: {
      type: Number as PropType<VimeoPlayerProperties['start']>,
      default: 0,
    },
  },
  emits: [...Object.keys(VIMEO_PLAYER_EVENTS)],
  setup(props, { emit }) {
    const container = ref(null)
    let player = null
    const eventHandlers = Object.entries(VIMEO_PLAYER_EVENTS).reduce(
      (acc, [event, value]) => {
        acc[value as keyof VimeoPlayerEvents] = (...args: any) => {
          emit(event as keyof VimeoPlayerEvents, ...args)
        }
        return acc
      },
      {} as { [K in keyof VimeoPlayerEvents]: (...args: any) => void }
    )
    const callback = () => {
      console.log('change')
    }
    watch(props, callback, { deep: true, immediate: true })
    onMounted(async () => {
      player = await VimeoPlayer.create(
        container.value as HTMLDivElement,
        VimeoPlayer.getInitialOptions(props),
        VimeoPlayer.getEventHandlers(eventHandlers)
      )
      // Player loaded
      if (player) emit('ready', player.instance)
    })

    onBeforeUnmount(() => {
      if (player) {
        player.instance.destroy()
      }
    })

    return {
      container,
    }
  },
})
</script>

// packages/svelte/src/Player.svelte
<script lang="ts">
  import {
    ImperativeHandle,
    VimeoPlayer,
    VIMEO_PLAYER_EVENTS,
  } from "@vimeo-player/core";
  import type {
    VimeoPlayerEvents,
    VimeoPlayerProperties,
  } from "@vimeo-player/core";
  import {
    onMount,
    createEventDispatcher,
    onDestroy,
    beforeUpdate,
  } from "svelte";

  let player: VimeoPlayer;
  let container: HTMLDivElement;

  const dispatch = createEventDispatcher<VimeoPlayerEvents>();

  /* ************ player properties ******************* */
  export let video: VimeoPlayerProperties["video"];
  export let volume: VimeoPlayerProperties["volume"] = 1;
  export let paused: VimeoPlayerProperties["paused"] = true;
  export let autopause: VimeoPlayerProperties["autopause"] = false;
  export let autoplay: VimeoPlayerProperties["autoplay"] = false;
  export let background: VimeoPlayerProperties["background"] = false;
  export let controls: VimeoPlayerProperties["controls"] = false;
  export let dnt: VimeoPlayerProperties["dnt"] = false;
  export let loop: VimeoPlayerProperties["loop"] = false;
  export let muted: VimeoPlayerProperties["muted"] = false;
  export let responsive: VimeoPlayerProperties["responsive"] = true;
  export let showByline: VimeoPlayerProperties["showByline"] = true;
  export let showPortrait: VimeoPlayerProperties["showPortrait"] = false;
  export let showTitle: VimeoPlayerProperties["showTitle"];
  export let speed: VimeoPlayerProperties["speed"] = false;
  export let texttrack: VimeoPlayerProperties["texttrack"] = "en";
  export let start: VimeoPlayerProperties["start"] = 0;

  /**************************************************** */

  export let ref: ImperativeHandle;

  let props = {
    video,
    volume,
    paused,
    autopause,
    autoplay,
    background,
    controls,
    dnt,
    loop,
    responsive,
    muted,
    showByline,
    showPortrait,
    showTitle,
    speed,
    start,
    texttrack,
  };

  const eventHandlers = Object.entries(VIMEO_PLAYER_EVENTS).reduce(
    (acc, [event, value]) => {
      acc[value as keyof VimeoPlayerEvents] = (...args: any) => {
        dispatch(event as keyof VimeoPlayerEvents, ...args);
      };
      return acc;
    },
    {} as { [K in keyof VimeoPlayerEvents]: (...args: any) => void }
  );

  onMount(async () => {
    player = await VimeoPlayer.create(
      container,
      VimeoPlayer.getInitialOptions(props),
      VimeoPlayer.getEventHandlers(eventHandlers)
    );

    ref = VimeoPlayer.imperativeHandle(player as VimeoPlayer);

    // Player loaded
    if (player) dispatch("ready", player.instance);
  });

  onDestroy(() => {
    if (player) {
      player.instance.destroy();
    }
  });

  beforeUpdate(() => {
    player?.update &&
      Object.values(VimeoPlayer.config)
        .filter(
          (name) =>
            $$props[name] !== undefined &&
            $$props[name] !== props[name as keyof typeof props]
        )
        .forEach((name: string) => {
          // @ts-ignore
          props[name] = $$props[name];
          //@ts-ignore
          player.update(name, props[name], {
            start: start,
            volume: volume,
          });
        });
  });
</script>

<div bind:this={container} />
