// packages/svelte/src/Player.svelte
<script lang="ts">
  import {
    ImperativeHandle,
    VimeoPlayer,
    VIMEO_PLAYER_EVENTS,
  } from "@vimeo-player/core";
  import type {
    VimeoPlayerEvents,
    VimeoPlayerProperties,
  } from "@vimeo-player/core";
  import {
    onMount,
    createEventDispatcher,
    onDestroy,
    beforeUpdate,
  } from "svelte";

  let player: VimeoPlayer;
  let container: HTMLDivElement;

  const dispatch = createEventDispatcher<VimeoPlayerEvents>();

  /* ************ player properties ******************* */
  export let video: VimeoPlayerProperties["video"];
  export let volume: VimeoPlayerProperties["volume"] = 1;
  export let paused: VimeoPlayerProperties["paused"] = true;
  export let autopause: VimeoPlayerProperties["autopause"] = false;
  export let autoplay: VimeoPlayerProperties["autoplay"] = false;
  export let background: VimeoPlayerProperties["background"] = false;
  export let controls: VimeoPlayerProperties["controls"] = false;
  export let dnt: VimeoPlayerProperties["dnt"] = false;
  export let loop: VimeoPlayerProperties["loop"] = false;
  export let muted: VimeoPlayerProperties["muted"] = false;
  export let responsive: VimeoPlayerProperties["responsive"] = true;
  export let showByline: VimeoPlayerProperties["showByline"] = true;
  export let showPortrait: VimeoPlayerProperties["showPortrait"] = false;
  export let showTitle: VimeoPlayerProperties["showTitle"];
  export let speed: VimeoPlayerProperties["speed"] = false;
  export let texttrack: VimeoPlayerProperties["texttrack"] = "en";
  export let start: VimeoPlayerProperties["start"] = 0;

  /**************************************************** */

  export let ref: ImperativeHandle;

  let props = {
    video,
    volume,
    paused,
    autopause,
    autoplay,
    background,
    controls,
    dnt,
    loop,
    responsive,
    muted,
    showByline,
    showPortrait,
    showTitle,
    speed,
    start,
    texttrack,
  };

  const eventHandlers = Object.entries(VIMEO_PLAYER_EVENTS).reduce(
    (acc, [event, value]) => {
      acc[value as keyof VimeoPlayerEvents] = (...args: any) => {
        dispatch(event as keyof VimeoPlayerEvents, ...args);
      };
      return acc;
    },
    {} as { [K in keyof VimeoPlayerEvents]: (...args: any) => void }
  );

  onMount(async () => {
    player = await VimeoPlayer.create(
      container,
      VimeoPlayer.getInitialOptions(props),
      VimeoPlayer.getEventHandlers(eventHandlers)
    );

    ref = VimeoPlayer.imperativeHandle(player as VimeoPlayer);

    // Player loaded
    if (player) dispatch("ready", player.instance);
  });

  onDestroy(() => {
    if (player) {
      player.instance.destroy();
    }
  });

  beforeUpdate(() => {
    player?.update &&
      Object.values(VimeoPlayer.config)
        .filter(
          (name) =>
            $$props[name] !== undefined &&
            $$props[name] !== props[name as keyof typeof props]
        )
        .forEach((name: string) => {
          // @ts-ignore
          props[name] = $$props[name];
          //@ts-ignore
          player.update(name, props[name], {
            start: start,
            volume: volume,
          });
        });
  });
</script>

<div bind:this={container} />

// packages/react/src/player.tsx
import * as React from "react";
import {
  VimeoPlayer,
  ImperativeHandle,
  VimeoPlayerOptions,
} from "@vimeo-player/core";

export interface PlayerProps extends VimeoPlayerOptions {
  as?: keyof JSX.IntrinsicElements | "div";
  id?: string;
  className?: string;
  style?: React.CSSProperties;
}

const Player = React.forwardRef<ImperativeHandle, PlayerProps>((props, ref) => {
  const {
    as = "div",
    start,
    volume,
    autopause,
    color,
    loop,
    muted,
    paused,
    video,
    id,
    className,
    style,
    height,
    width,
  } = props;
  const container = React.useRef<HTMLElement | null>(null);
  const player = React.useRef<VimeoPlayer | null>(null);
  const mounted = React.useRef<boolean>(false);

  const prevProps = React.useRef({
    autopause,
    color,
    loop,
    muted,
    paused,
    video,
    volume,
  });

  React.useEffect(() => {
    if (container.current) {
      player.current = VimeoPlayer.create(
        container.current,
        VimeoPlayer.getInitialOptions(props),
        VimeoPlayer.getEventHandlers(props)
      );
    }

    return () => {
      player.current?.instance.destroy();
      player.current = null;
      container.current = null;
    };
  }, []);

  // componentDidUpdate Equivalent
  React.useEffect(() => {
    if (!mounted.current) {
      mounted.current = true;
    } else {
      Object.values(VimeoPlayer.config)
        //@ts-ignore TODO check how tslint error can be fix
        .filter((name) => props[name] !== prevProps.current[name])
        .map((name) => {
          //@ts-ignore TODO check how tslint error can be fix
          prevProps.current[name] = props[name];
          //@ts-ignore TODO check how tslint error can be fix
          player.current.update(name, props[name], {
            start: start,
            volume: volume,
          });
        });
    }
  }, [autopause, color, loop, muted, paused, video, volume, height, width]);

  React.useImperativeHandle(
    ref,
    () => VimeoPlayer.imperativeHandle(player.current as VimeoPlayer),
    []
  );

  return React.createElement(as, {
    ref: container,
    className,
    id,
    style,
  });
});

Player.defaultProps = {
  autopause: true,
  autoplay: false,
  background: false,
  controls: false,
  dnt: false,
  loop: false,
  muted: false,
  // If responsive is set to true, height and width is not respected
  responsive: true,
  showByline: true,
  showPortrait: true,
  showTitle: true,
  speed: true,
  volume: 1,
  language: "en",
};

export { Player };
